Formik
Racenna/social_network pull request #5
Opened 2021-01-11 18:42 UTC by Racenna

2021-01-11 18:54 UTC, worksnk requested changes

2021-01-11 18:54 UTC, worksnk commented on src/components/Profile/MyPosts/MyPostForm/MyPostsForm.jsx
> +        if (values.post.length === 0 || values.post.trim() === '') return;
this should be part of your validation

2021-01-11 18:54 UTC, worksnk commented on src/components/Profile/MyPosts/MyPostForm/MyPostsForm.jsx
> +    <Formik
use hook API

2021-01-11 18:54 UTC, worksnk commented on src/components/Profile/ProfileInfo/ProfileInfo.jsx
> +            // initialValues={profile}
always remove commented code

2021-01-11 18:54 UTC, worksnk commented on src/redux/profileReducer.js
> +    // const message =
remove commented code

2021-01-11 18:54 UTC, worksnk commented on src/util/validator/validators.js
> +export const profileDescriptionValidate = (values) => {
Use field level validation

2021-01-11 18:54 UTC, worksnk commented on src/util/validator/validators.js
> +export const profileDescriptionValidate = (values) => {
And read about validationSchema in formik documentation

2021-01-11 18:54 UTC, worksnk commented on src/components/Profile/ProfileInfo/ProfileDescription/ProfileDescriptionForm.jsx
> +                {Object.keys(values.contacts).map((key) => {
read documentation for formik https://formik.org/docs/guides/arrays

2021-01-11 18:56 UTC, Racenna commented on src/components/Profile/MyPosts/MyPostForm/MyPostsForm.jsx
> +        if (values.post.length === 0 || values.post.trim() === '') return;
forgot to remove

2021-01-12 17:46 UTC, Racenna commented on src/components/Profile/MyPosts/MyPostForm/MyPostsForm.jsx
> +    <Formik
Replaced Formik with useFormik

2021-01-12 17:46 UTC, Racenna commented on src/components/Profile/ProfileInfo/ProfileInfo.jsx
> +            // initialValues={profile}
Removed comments in code

2021-01-12 17:48 UTC, Racenna commented on src/redux/profileReducer.js
> +    // const message =
Removed comments in code

2021-01-12 18:50 UTC, worksnk commented on src/components/Profile/ProfileInfo/ProfileInfo.jsx
> +            // initialValues={profile}
But it's right here. It wasn't removed

2021-01-12 18:51 UTC, worksnk commented on src/redux/profileReducer.js
> +    // const message =
same as before

2021-01-12 18:51 UTC, worksnk commented on src/components/Profile/ProfileInfo/ProfileDescription/ProfileDescriptionForm.jsx
> +                {Object.keys(values.contacts).map((key) => {
read the doc and check if you can improve it

2021-01-12 18:52 UTC, worksnk commented on src/components/Profile/ProfileInfo/ProfileDescription/ProfileDescriptionForm.jsx
> +                {Object.keys(values.contacts).map((key) => {
Also you didn't change to formik hooks here. When I leave a comment I'm not going to comment each single time it happens. I expect you finding places like this and fixing them

2021-01-12 19:11 UTC, Racenna commented on src/components/Profile/ProfileInfo/ProfileDescription/ProfileDescriptionForm.jsx
> +                {Object.keys(values.contacts).map((key) => {
I must use useField here?

2021-01-12 19:33 UTC, worksnk commented on src/components/Profile/ProfileInfo/ProfileDescription/ProfileDescriptionForm.jsx
> +                {Object.keys(values.contacts).map((key) => {
Use yup. Read about how to work with arrays and check see how you can change your component

2021-01-13 08:47 UTC, worksnk commented
@Racenna Don't forget to remove redux-form from the project. Remove it from dependecies

2021-01-13 09:01 UTC, worksnk commented on package.json
>      "redux-form": "^8.3.6",
remove it

2021-01-13 17:06 UTC, Racenna commented on package.json
>      "redux-form": "^8.3.6",
removed

2021-01-13 17:54 UTC, worksnk approved these changes

2021-01-13 17:56 UTC, merged