Redux structure
Racenna/social_network pull request #6
Opened 2021-01-13 20:03 UTC by Racenna

2021-01-15 08:59 UTC, worksnk requested changes

2021-01-15 08:59 UTC, worksnk commented on src/redux/appReducer/actions.js
> +  Promise.all([promise]).then(() => {
Why you use `Promise.all` here?

2021-01-15 08:59 UTC, worksnk commented on src/redux/authReducer/index.js
> +export {
Why do you export them from index one by one?

2021-01-18 12:26 UTC, Racenna commented on src/redux/appReducer/actions.js
> +  Promise.all([promise]).then(() => {
Changed it

2021-01-18 12:27 UTC, Racenna commented on src/redux/authReducer/index.js
> +export {
Used aggregating modules how in example on MDN

2021-01-18 18:51 UTC, worksnk commented on src/components/Dialogs/Dialogs.jsx
> +import { dialogsDataSelector } from '../../redux/dialogsReducer/index';
you don't need to specify `index`. Index is loaded by default if directory specified as import path

2021-01-18 18:54 UTC, worksnk commented on src/redux/appReducer/reducer.js
> +    case SET_INITIALIZED:
Why do you need this state in the first place?

2021-01-18 18:57 UTC, worksnk approved these changes

2021-01-18 19:09 UTC, merged