Url pagination
Racenna/social_network pull request #7
Opened 2021-01-14 12:24 UTC by Racenna

2021-01-15 09:36 UTC, worksnk commented on src/components/Users/UsersContainer.jsx
> +    const parsed = queryString.parse(history.location.search);
knowing about queryString is good. But I want you to use build capabilities to work with query

Also I'm not sure why you use history if you need location. Just use location hook directly

2021-01-15 09:36 UTC, worksnk commented on src/components/Users/UsersContainer.jsx
> +  useEffect(() => {
Why do you trigger it on each render of component?

Also change it to be declarative

2021-01-15 09:40 UTC, worksnk requested changes

2021-01-15 09:40 UTC, worksnk commented on src/components/Users/UsersContainer.jsx
> +    dispatch(getUsers(actualPage, pageSize));
In general this is incorrect you want refetch when currentPage is changed and that's it

2021-01-16 15:47 UTC, Racenna commented on src/components/Users/UsersContainer.jsx
> +    const parsed = queryString.parse(history.location.search);
replaced history with location

2021-01-16 15:48 UTC, Racenna commented on src/components/Users/UsersContainer.jsx
> +  useEffect(() => {
added dependecy in useEffect

2021-01-17 13:26 UTC, worksnk commented on src/redux/usersReducer/selectors.js
> +export const getCurrentPageSelector = (state) => state.usersData.currentPage;
Don't store it redux

2021-01-17 13:27 UTC, worksnk commented on src/redux/profileReducer/reducer.js
> +            id: 65,
why you put always the same id?

2021-01-17 13:29 UTC, worksnk commented on src/components/Users/UsersContainer.jsx
>      history.push({
Don't use history push. It must redirect to url when clicked. Declrative

2021-01-19 19:35 UTC, worksnk approved these changes

2021-01-19 19:36 UTC, merged